use super::*;

/// The widgets and shared handles the reader's wiring functions work on. Every field is a
/// cheap reference-counted handle (or a small value), so a function destructures what it
/// needs and clones from it.
#[derive(Clone)]
pub(super) struct PdfUi {
    pub(super) host: Rc<dyn ReaderHost>,
    pub(super) reader: Rc<RefCell<ReaderState>>,
    pub(super) reader_tab: crate::reader_host::ReaderTab,
    pub(super) reader_window: adw::Window,
    pub(super) render: Rc<dyn Fn()>,
    pub(super) undo: Rc<dyn Fn()>,
    pub(super) redo: Rc<dyn Fn()>,
    pub(super) quick_mark: QuickMarkSlot,
    pub(super) reflow_popover: RebuildNotesCell,
    pub(super) mode_change: crate::RebuildCell,
    pub(super) palette_choice: Rc<Cell<Option<usize>>>,
    pub(super) palette: gtk4::Box,
    pub(super) style_drop: gtk4::DropDown,
    pub(super) rebuild_notes: Rc<dyn Fn()>,
    pub(super) view: adw::ToolbarView,
    pub(super) prev: gtk4::Button,
    pub(super) next: gtk4::Button,
    pub(super) page_entry: gtk4::Entry,
    pub(super) page_of_label: gtk4::Label,
    pub(super) bookmark_button: gtk4::Button,
    pub(super) zoom_out: gtk4::Button,
    pub(super) zoom_in: gtk4::Button,
    pub(super) zoom_fit_width: gtk4::Button,
    pub(super) zoom_fit_page: gtk4::Button,
    pub(super) rotate_button: gtk4::Button,
    pub(super) invert_button: gtk4::ToggleButton,
    pub(super) note_button: gtk4::Button,
    pub(super) page_num_button: gtk4::Button,
    pub(super) sidebar_toggle: gtk4::ToggleButton,
    pub(super) notes_toggle: gtk4::ToggleButton,
    pub(super) continuous_toggle: gtk4::ToggleButton,
    pub(super) text_toggle: gtk4::ToggleButton,
    pub(super) two_page_toggle: gtk4::ToggleButton,
    pub(super) popout_button: gtk4::Button,
    pub(super) export_button: gtk4::Button,
    pub(super) search_entry: gtk4::SearchEntry,
    pub(super) search_prev: gtk4::Button,
    pub(super) search_next: gtk4::Button,
    pub(super) search_count: gtk4::Label,
    pub(super) link_back: gtk4::Button,
    pub(super) link_forward: gtk4::Button,
    pub(super) hint: gtk4::Label,
    pub(super) picture: gtk4::Picture,
    pub(super) scroll: gtk4::ScrolledWindow,
    pub(super) continuous_box: gtk4::Box,
    pub(super) continuous_scroll: gtk4::ScrolledWindow,
    pub(super) view_stack: gtk4::Stack,
    pub(super) notes_scroll: gtk4::ScrolledWindow,
    pub(super) notes_paned: gtk4::Paned,
    pub(super) paned: gtk4::Paned,
    pub(super) split_paned: gtk4::Paned,
    pub(super) split_side_button: gtk4::Button,
    pub(super) split_stack_button: gtk4::Button,
    pub(super) pdf_hash: String,
    pub(super) title: String,
    pub(super) window: adw::ApplicationWindow,
    pub(super) drag_preview: gtk4::DrawingArea,
    pub(super) drag_live_rect: DragRectCell,
    pub(super) sidebar_box: gtk4::Box,
}
