#!/usr/bin/env python3
"""Generate crates/fond-read-gtk/src/pdfium_lock.rs from the pinned pdfium-render source.

PDFium is not thread-safe, and pdfium-render's `thread_safe` feature only locks library
init/teardown, not each call. LockedBindings wraps every required method of
PdfiumLibraryBindings in one process-wide mutex so the GTK thread and the render thread can
share a Pdfium. Regenerate when the pdfium-render version in Cargo.lock changes:

    tools/gen_pdfium_lock.py ~/.cargo/registry/src/*/pdfium-render-<version>/src/bindings.rs
"""
import re, sys, pathlib

src = pathlib.Path(sys.argv[1]).read_text().split("\n")
start = next(i for i, l in enumerate(src) if l.startswith("pub trait PdfiumLibraryBindings"))
end = next(i for i in range(start + 1, len(src)) if src[i] == "}")
body = src[start + 1:end]

methods = []
i = 0
attrs = []
while i < len(body):
    l = body[i]
    if l.startswith("    #["):
        # an attribute, possibly multi-line
        a = l
        while a.count("(") > a.count(")") or a.count("[") > a.count("]"):
            i += 1
            a += "\n" + body[i]
        attrs.append(a)
        i += 1
        continue
    if l.startswith("    ///") or l.strip() == "":
        i += 1
        continue
    if re.match(r"^    (unsafe )?fn ", l):
        sig = l
        j = i
        while not (sig.rstrip().endswith(";") or "{" in re.sub(r"//.*", "", sig)):
            j += 1
            sig += "\n" + body[j]
        if sig.rstrip().endswith(";"):
            methods.append((attrs, sig.rstrip()[:-1]))
            attrs = []
            i = j + 1
        else:
            # a default method with a body: skip to its closing brace
            code = lambda t: re.sub(r"//.*", "", t)
            depth = code(sig).count("{") - code(sig).count("}")
            while depth > 0:
                j += 1
                depth += code(body[j]).count("{") - code(body[j]).count("}")
            attrs = []
            i = j + 1
        continue
    i += 1


ACTIVE = {"pdfium_7543", "pdfium_latest", "sync", "thread_safe"}


def eval_cfg(expr):
    """Evaluate a #[cfg(...)] predicate for the features this build enables."""
    toks = re.findall(r'[A-Za-z_][A-Za-z_0-9]*|"[^"]*"|[(),=]', expr)
    pos = 0

    def parse():
        nonlocal pos
        name = toks[pos]
        pos += 1
        if name in ("any", "all", "not"):
            assert toks[pos] == "("
            pos += 1
            vals = []
            while toks[pos] != ")":
                vals.append(parse())
                if toks[pos] == ",":
                    pos += 1
            pos += 1
            return any(vals) if name == "any" else all(vals) if name == "all" else not vals[0]
        if pos < len(toks) and toks[pos] == "=":
            pos += 1
            val = toks[pos].strip('"')
            pos += 1
            if name == "feature":
                return val in ACTIVE
            if name == "target_arch":
                return val == "x86_64"
            return False
        return False  # doc, test, ...

    return parse()


def enabled(attrs):
    for a in attrs:
        m = re.match(r"\s*#\[cfg\((.*)\)\]", re.sub(r"//.*", "", a), re.S)
        if m and not eval_cfg(re.sub(r"\s+", " ", m.group(1))):
            return False
    return True


def split_top(s):
    out, depth, cur = [], 0, ""
    for ch in s:
        if ch in "(<[":
            depth += 1
        elif ch in ")>]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return out


out = ["// @generated by tools/gen_pdfium_lock.py — do not edit.", "#![allow(non_snake_case, deprecated, clippy::too_many_arguments, clippy::missing_safety_doc)]", "",
       "use pdfium_render::prelude::*;", "use std::os::raw::*;", "#[allow(non_camel_case_types)]", "type size_t = usize;",
       "use std::sync::{Mutex, MutexGuard};", "",
       "static PDFIUM_CALL_LOCK: Mutex<()> = Mutex::new(());", "",
       "fn lock() -> MutexGuard<'static, ()> {", "    PDFIUM_CALL_LOCK.lock().unwrap_or_else(|e| e.into_inner())", "}", "",
       "/// Every PDFium call made through this takes one process-wide lock, so any number of threads can share a `Pdfium`.",
       "pub struct LockedBindings(pub Box<dyn PdfiumLibraryBindings>);", "",
       "impl PdfiumLibraryBindings for LockedBindings {"]
kept = 0
for attrs, sig in methods:
    if not enabled(attrs):
        continue
    kept += 1
    m = re.match(r"\s*(unsafe )?fn (\w+)\s*\((.*?)\)\s*(->\s*.*)?$", sig, re.S)
    uns, name, params, ret = m.group(1) or "", m.group(2), m.group(3), m.group(4) or ""
    ps = split_top(params)
    names = []
    for p in ps:
        p = p.strip()
        if p in ("&self", "&mut self"):
            continue
        names.append(p.split(":", 1)[0].strip().removeprefix("mut "))
    out.append("    #[inline]")
    out.append(f"    {uns}fn {name}({params.strip()}) {ret.strip()} {{")
    call = f"self.0.{name}({', '.join(names)})"
    out.append(f"        let _guard = lock();")
    out.append(f"        {'unsafe { ' + call + ' }' if uns else call}")
    out.append("    }")
out.append("}")
pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else "pdfium_lock.rs").write_text("\n".join(out) + "\n")
print(f"{kept} of {len(methods)} methods enabled")
